#!/usr/local/bin/perl

use 5.010;
use strict;
use warnings FATAL => 'all';

use Test::More;

use_ok('Authy::Text');
use Authy::Text;

isnt(msg(MSG_PROMPT_ENTER_METHOD, ('_') x 5), undef, "MSG_PROMPT_ENTER_METHOD");
isnt(msg(MSG_PROMPT_INVALID_METHOD, ('_') x 5), undef, "MSG_PROMPT_INVALID_METHOD");
isnt(msg(MSG_PROMPT_ENTER_OTP, ('_') x 5), undef, "MSG_PROMPT_ENTER_OTP");
isnt(msg(MSG_PROMPT_INCORRECT_OTP, ('_') x 5), undef, "MSG_PROMPT_INCORRECT_OTP");
isnt(msg(MSG_PROMPT_ONE_TOUCH, ('_') x 5), undef, "MSG_PROMPT_ONE_TOUCH");
isnt(msg(MSG_PROMPT_ONE_TOUCH_EXPIRED, ('_') x 5), undef, "MSG_PROMPT_ONE_TOUCH_EXPIRED");

isnt(msg(MSG_RESULT_SUCCEEDED, ('_') x 5), undef, "MSG_RESULT_SUCCEEDED");
isnt(msg(MSG_RESULT_FAILED, ('_') x 5), undef, "MSG_RESULT_FAILED");
isnt(msg(MSG_RESULT_NO_ID, ('_') x 5), undef, "MSG_RESULT_NO_ID");
isnt(msg(MSG_RESULT_ERROR, ('_') x 5), undef, "MSG_RESULT_ERROR");

isnt(err(ERR_ID_STORE_MODULE_LOAD_FAILED, ('_') x 5), undef, "ERR_ID_STORE_MODULE_LOAD_FAILED");
isnt(err(ERR_ID_STORE_INVALID_MODULE, ('_') x 5), undef, "ERR_ID_STORE_INVALID_MODULE");
isnt(err(ERR_ID_STORE_INITIALIZATION_FAILED, ('_') x 5), undef, "ERR_ID_STORE_INITIALIZATION_FAILED");

isnt(err(ERR_AUTH_NO_USER_NAME_IN_REQUEST, ('_') x 5), undef, "ERR_AUTH_NO_USER_NAME_IN_REQUEST");
isnt(err(ERR_AUTH_NO_PASSWORD_IN_REQUEST, ('_') x 5), undef, "ERR_AUTH_NO_PASSWORD_IN_REQUEST");
isnt(err(ERR_AUTH_NO_ID_IN_REQUEST, ('_') x 5), undef, "ERR_AUTH_NO_ID_IN_REQUEST");
isnt(err(ERR_AUTH_NO_OTP_IN_REQUEST, ('_') x 5), undef, "ERR_AUTH_NO_OTP_IN_REQUEST");
isnt(err(ERR_AUTH_NO_CHALLENGE_RESPONSE_IN_REQUEST, ('_') x 5), undef, "ERR_AUTH_NO_CHALLENGE_RESPONSE_IN_REQUEST");
isnt(err(ERR_AUTH_UNEXPECTED_OTP_IN_REQUEST, ('_') x 5), undef, "ERR_AUTH_UNEXPECTED_OTP_IN_REQUEST");
isnt(err(ERR_AUTH_ID_RETRIEVAL_FAILED, ('_') x 5), undef, "ERR_AUTH_ID_RETRIEVAL_FAILED");
isnt(err(ERR_AUTH_INVALID_ID, ('_') x 5), undef, "ERR_AUTH_INVALID_ID");
isnt(err(ERR_AUTH_INVALID_STATE, ('_') x 5), undef, "ERR_AUTH_INVALID_STATE");

isnt(err(ERR_OTP_PROMPT_REQUEST_FAILED_INTERNALLY, ('_') x 5), undef, "ERR_OTP_PROMPT_REQUEST_FAILED_INTERNALLY");
isnt(err(ERR_OTP_PROMPT_REQUEST_FAILED_EXTERNALLY, ('_') x 5), undef, "ERR_OTP_PROMPT_REQUEST_FAILED_EXTERNALLY");
isnt(err(ERR_OTP_VERIFICATION_REQUEST_FAILED_INTERNALLY, ('_') x 5), undef, "ERR_OTP_VERIFICATION_REQUEST_FAILED_INTERNALLY");
isnt(err(ERR_OTP_VERIFICATION_REQUEST_FAILED_EXTERNALLY, ('_') x 5), undef, "ERR_OTP_VERIFICATION_REQUEST_FAILED_EXTERNALLY");

isnt(err(ERR_ONE_TOUCH_APPROVAL_REQUEST_CREATION_FAILED_INTERNALLY, ('_') x 5), undef, "ERR_ONE_TOUCH_APPROVAL_REQUEST_CREATION_FAILED_INTERNALLY");
isnt(err(ERR_ONE_TOUCH_APPROVAL_REQUEST_CREATION_FAILED_EXTERNALLY, ('_') x 5), undef, "ERR_ONE_TOUCH_APPROVAL_REQUEST_CREATION_FAILED_EXTERNALLY");
isnt(err(ERR_ONE_TOUCH_API_ENDPOINT_FAILED_INTERNALLY, ('_') x 5), undef, "ERR_ONE_TOUCH_API_ENDPOINT_FAILED_INTERNALLY");
isnt(err(ERR_ONE_TOUCH_API_ENDPOINT_FAILED_EXTERNALLY, ('_') x 5), undef, "ERR_ONE_TOUCH_API_ENDPOINT_FAILED_EXTERNALLY");
isnt(err(ERR_ONE_TOUCH_CUSTOM_ENDPOINT_FAILED_INTERNALLY, ('_') x 5), undef, "ERR_ONE_TOUCH_CUSTOM_ENDPOINT_FAILED_INTERNALLY");
isnt(err(ERR_ONE_TOUCH_CUSTOM_ENDPOINT_FAILED_EXTERNALLY, ('_') x 5), undef, "ERR_ONE_TOUCH_CUSTOM_ENDPOINT_FAILED_EXTERNALLY");
isnt(err(ERR_ONE_TOUCH_ENDPOINT_RETURNED_INVALID_STATUS, ('_') x 5), undef, "ERR_ONE_TOUCH_ENDPOINT_RETURNED_INVALID_STATUS");

done_testing();
